import { test, expect } from '@playwright/test';
/*test('test', async ({ page }) => {
  await page.goto('https://uat.quiklyz.com/');
  await page.locator('input[placeholder="Search Your City"]').fill('Chennai');
  await page.locator('.fg-line-form > div > div > .Chennai > div').first().click();
});*/
test.only('login',async ({ page }) => {
  //Signup
  await page.goto('https://uat.quiklyz.com/');
  await page.locator('input[placeholder="Search Your City"]').fill('Chennai');
  await page.locator('.fg-line-form > div > div > .Chennai > div').first().click();
  await page.getByRole('button', { name: 'Login ' }).click();
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.getByRole('textbox', { name: 'Enter Mobile Number' }).fill('8754372815');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('(//input[@id="otpField-0"])[1]').fill('1');
  await page.locator('(//input[@id="otpField-1"])[1]').fill('2');
  await page.locator('(//input[@id="otpField-2"])[1]').fill('3');
  test.setTimeout(130000);
  await page.locator('(//input[@id="otpField-3"])[1]').fill('4');
  await page.locator('(//input[@id="otpField-4"])[1]').fill('5');
  await page.locator('(//input[@id="otpField-5"])[1]').fill('6');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  //car selection
//   await page.locator("//span[text()=' Audi (1) ']").check();
//   await page.getByText('SUV (28)').click();
//   await page.getByLabel('Automatic (51)').check();
//   await page.getByLabel('Electric (9)').check();
//   await page.locator("//a[text()='Audi e-tron ']").click();
//   //await page.getByRole('button', { name: 'SE ' }).click();
//  //await page.locator('li').filter({ hasText: 'I-Pace SE Electric Automatic Metallic Active ₹ 296,299 /month' }).locator('div').nth(1).click();
//   await page.getByText('48 Select Tenure (Months)').click();
//   await page.getByRole('option', { name: '36' }).click();
//   await page.getByText('10,000 km/year').click();
//   await page.getByText('15,000 km/year').click();
//   await page.locator("(//mat-select-trigger[text()=' Assured Buyback '])[2]").click();
//   await page.locator("//span[text()='Flexi Advantage ']").click();
//check my eligibility
//   await page.locator("(//span[text()=' Check my Eligibility '])[1]").click();
  // await page.locator("//input[@name='PAN_NO_5d3d4a20-c8b1-4e61-9a51-564899597612']").fill('IVIPS4490D');
  // await page.getByLabel('Open calendar').click();
  // await page.getByLabel('Choose month and year').click();
  // await page.locator("//div[text()=' 1998 ']").click();
  // await page.getByLabel('December 1998').click();
  // await page.getByLabel('10 December 1998', { exact: true }).click();
  // //await page.getByLabel('11 September 2023').click();
  // await page.locator('#mat-checkbox-6 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  // await page.getByRole('button', { name: 'Edit Record' }).click();
  //check eligibility and reserve
  // await page.locator("//input[@name='RM_ADDRESS_LINE1_599ec899-409f-49eb-ac88-2820bd813775']").fill('1/89A, vivekanatha street');
  // await page.locator("//input[@name='RM_CITY_8d1739d1-dd9c-4f81-8214-38eed5006cc3']").fill('chennai');
  // await page.locator("//input[@name='RM_PINCODE_97a54ab1-f72a-4d86-8541-3d93f5c9cef3']").fill('600110');
  // await page.locator("//span[@class='mat-select-placeholder mat-select-min-line ng-tns-c71-90 ng-star-inserted']").click();
  // await page.locator("//span[text()=' Tamil Nadu ']").click();
  // await page.locator("(//span[text()='Continue'])[1]").click();
  //Employeement status
  //await page.locator("(//span[text()='Continue'])[1]").click();
  //income validation
  await page.locator('#mat-checkbox-6 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.locator("(//button[text()='Continue'])[1]").click();
  await page.pause();
  // await page.goBack();
  // await page.getByRole('button', { name: 'OK' }).click();
});
test('register',async ({ page }) => {
  //Register
  await page.goto('https://uat.quiklyz.com/');
  await page.locator('input[placeholder="Search Your City"]').fill('Chennai');
  await page.locator('.fg-line-form > div > div > .Chennai > div').first().click();
  await page.locator("//span[text()='Login  ']").click();
  await page.locator('//span[text()=" Start here"]').click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('soundara');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('rajan');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('msrajan606@gmail.com');
  await page.getByRole('textbox', { name: 'Enter your Mobile Number' }).fill('8754372815');
  await page.locator("(//span[@class='mat-checkbox-inner-container'])[1]").click();
  await page.locator("(//span[text()='Register'])[1]").click();
  await page.locator('(//input[@id="otpField-0"])[1]').fill('1');
  await page.locator('(//input[@id="otpField-1"])[1]').fill('2');
  await page.locator('(//input[@id="otpField-2"])[1]').fill('3');
  await page.locator('(//input[@id="otpField-3"])[1]').fill('4');
  await page.locator('(//input[@id="otpField-4"])[1]').fill('5');
  await page.locator('(//input[@id="otpField-5"])[1]').fill('6');
  await page.locator("//button[@class='mat-focus-indicator mat-flat-button mat-button-base mat-primary ng-star-inserted']").click();
   test.setTimeout(150000);
});
test('Find cars',async ({ page }) => {
//    //Find cars
  await page.goto('https://uat.quiklyz.com/');
  await page.locator('input[placeholder="Search Your City"]').fill('Chennai');
  await page.locator('.fg-line-form > div > div > .Chennai > div').first().click();
  await page.locator("(//a[@class='mat-focus-indicator mat-button mat-button-base ng-star-inserted'])[1]").click();
  await page.locator('.mat-slider-thumb').first().dragTo(page.locator('mat-slider:nth-child(2) > .mat-slider-wrapper > .mat-slider-ticks-container > .mat-slider-ticks'));
  await page.locator("//span[text()=' Audi (1) ']").check();
  await page.getByText('SUV (28)').click();
  await page.getByLabel('Automatic (51)').check();
  await page.getByLabel('Electric (9)').check();
  await page.locator("//a[text()='Audi e-tron ']").click();
  //await page.getByRole('button', { name: 'SE ' }).click();
 //await page.locator('li').filter({ hasText: 'I-Pace SE Electric Automatic Metallic Active ₹ 296,299 /month' }).locator('div').nth(1).click();
  await page.getByText('48 Select Tenure (Months)').click();
  await page.getByRole('option', { name: '36' }).click();
  await page.getByText('10,000 km/year').click();
  await page.getByText('15,000 km/year').click();
  await page.locator("(//mat-select-trigger[text()=' Assured Buyback '])[2]").click();
  await page.locator("//span[text()='Flexi Advantage ']").click();
  await page.goBack();
 // await page.locator('.mat-slider-thumb').first().dragTo(page.locator('mat-slider').filter({ hasText: '500000' }));
  //test.setTimeout(13000);
  await page.locator("//span[text()=' Honda (2) ']").check();
  
  await page.locator("//span[text()=' AMT (21) ']").check();
  await page.locator("//span[text()=' CNG (13) ']").check();
  await page.locator("//span[text()=' Clear All ']").click();
  await page.locator("//span[text()=' Mahindra (10) ']").check();
  console.log(  await page.locator("//span[text()=' Mahindra (10) ']").textContent());
  console.log(await page.locator('//div[@class="col-md-8 text-right facet-label-wrapper"]').textContent());
  await page.locator('mat-slider:nth-child(2) > .mat-slider-wrapper > .mat-slider-thumb-container > .mat-slider-thumb').dragTo(page.locator('mat-slider:nth-child(2) > .mat-slider-wrapper > .mat-slider-ticks-container > .mat-slider-ticks'));
  console.log(await page.locator("//div[@class='col-md-8 text-right facet-label-wrapper']").textContent());
  //console.log(await page.locator('mat-slider').filter({ hasText: '253255' }).textContent());
  
  await page.locator("//span[text()=' Audi (1) ']").check();
  await page.locator("//span[text()=' Honda (2) ']").check();
  await page.locator("//span[text()=' Hyundai (11) ']").check();
  await page.locator("//span[text()=' Jaguar (1) ']").check();
  await page.locator("//span[text()=' Jeep (2) ']").check();
  await page.locator("//span[text()=' Kia (3) ']").check();
  await page.locator("//span[text()=' MG (6) ']").check();
  await page.locator("//span[text()=' Mahindra (10) ']").check();
  await page.locator("//span[text()=' Maruti Suzuki (11) ']").check();
  await page.locator("//span[text()=' Nissan (1) ']").check();
  await page.locator("//span[text()=' Renault (3) ']").check();
  await page.locator("//span[text()=' Skoda (3) ']").check();
  await page.locator("//span[text()=' Tata (10) ']").check();
  await page.locator("//span[text()=' Toyota (4) ']").check();
  await page.locator("//span[text()=' Volkswagen (2) ']").check();
  await page.locator("//span[text()=' Clear All ']").click();

  // await page.locator("//input[@name='inlineSearchField']").fill('Mahendra');
  // await page.locator("//span[text()='Sort by Popularity']").click();
  
  // //await page.pause();
  // const car = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  // const title=await car.allTextContents();
  // console.log(title);
  
  // await page.locator("//span[text()=' Latest Additions ']").click();
  // await page.pause();
  // await page.locator('locator("#mat-select-value-15")').click();
  // await page.locator("//span[text()=' Sort by Price Low to High ']").click();
  
  
  // await page.locator('.fgcustomsort > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click();
  // await page.locator("//span[text()=' Sort by Price High to Low ']").click();
});
test('check the cars',async ({ page }) => {
  await page.goto('https://uat.quiklyz.com/');
  await page.locator('input[placeholder="Search Your City"]').fill('Chennai');
  await page.locator('.fg-line-form > div > div > .Chennai > div').first().click();
  await page.locator("(//a[@class='mat-focus-indicator mat-button mat-button-base ng-star-inserted'])[1]").click();
 test.setTimeout(70000);
     console.log(await page.locator('//div[@class="col-md-8 text-right facet-label-wrapper"]').textContent());

  //Brand
  await page.locator("//span[text()=' Audi (1) ']").check();
  console.log(await page.locator("//span[text()=' Audi (1) ']").textContent());
  await page.waitForTimeout(3000);
  const car1 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title1=await car1.allTextContents();
  console.log(title1.length);
  console.log(title1);
  await page.locator("//span[text()=' Audi (1) ']").uncheck();
  await page.locator("//span[text()=' Honda (2) ']").check();
  console.log(await page.locator("//span[text()=' Honda (2) ']").textContent());
  await page.waitForTimeout(3000);
  const car2 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title2=await car2.allTextContents();
  console.log(title2.length);
  console.log(title2);
  await page.locator("//span[text()=' Honda (2) ']").uncheck();
  await page.locator("//span[text()=' Hyundai (11) ']").check();
  console.log(await page.locator("//span[text()=' Hyundai (11) ']").textContent());
  await page.waitForTimeout(3000);
  const car3 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title3=await car3.allTextContents();
  console.log(title3.length);
  console.log(title3);
  await page.locator("//span[text()=' Hyundai (11) ']").uncheck();
  await page.locator("//span[text()=' Jaguar (1) ']").check();
  console.log(await page.locator("//span[text()=' Jaguar (1) ']").textContent());
  await page.waitForTimeout(3000);
  const car4 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title4=await car4.allTextContents();
  console.log(title4.length);
  console.log(title4);
  await page.locator("//span[text()=' Jaguar (1) ']").uncheck();
  await page.locator("//span[text()=' Jeep (2) ']").check();
  console.log(await page.locator("//span[text()=' Jeep (2) ']").textContent());
  await page.waitForTimeout(3000);
  const car5 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title5=await car5.allTextContents();
  console.log(title5.length);
  console.log(title5);
  await page.locator("//span[text()=' Jeep (2) ']").uncheck();
  await page.locator("//span[text()=' Kia (3) ']").check();
  console.log(await page.locator("//span[text()=' Kia (3) ']").textContent());
  await page.waitForTimeout(3000);
  const car6 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title6=await car6.allTextContents();
  console.log(title6.length);
  console.log(title6);
  await page.locator("//span[text()=' Kia (3) ']").uncheck();
  await page.locator("//span[text()=' MG (6) ']").check();
  console.log(await page.locator("//span[text()=' MG (6) ']").textContent());
  await page.waitForTimeout(3000);
  const car7 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title7=await car7.allTextContents();
  console.log(title7.length);
  console.log(title7);
  await page.locator("//span[text()=' MG (6) ']").uncheck();
  await page.locator("//span[text()=' Mahindra (10) ']").check();
  console.log(await page.locator("//span[text()=' Mahindra (10) ']").textContent());
  await page.waitForTimeout(3000);
  const car8 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title8=await car8.allTextContents();
  console.log(title8.length);
  console.log(title8);
  await page.locator("//span[text()=' Mahindra (10) ']").uncheck();
  await page.locator("//span[text()=' Maruti Suzuki (11) ']").check();
  console.log(await page.locator("//span[text()=' Maruti Suzuki (11) ']").textContent());
  await page.waitForTimeout(3000);
  const car9 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title9=await car9.allTextContents();
  console.log(title9.length);
  console.log(title9);
  await page.locator("//span[text()=' Maruti Suzuki (11) ']").uncheck();
  await page.locator("//span[text()=' Nissan (1) ']").check();
  console.log(await page.locator("//span[text()=' Nissan (1) ']").textContent());
  await page.waitForTimeout(3000);
  const car10 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title10=await car10.allTextContents();
  console.log(title10.length);
  console.log(title10);
  await page.locator("//span[text()=' Nissan (1) ']").uncheck();
  await page.locator("//span[text()=' Renault (3) ']").check();
  console.log(await page.locator("//span[text()=' Renault (3) ']").textContent());
  await page.waitForTimeout(3000);
  const car11 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title11=await car11.allTextContents();
  console.log(title11.length);
  console.log(title11);
  await page.locator("//span[text()=' Renault (3) ']").uncheck();
  await page.locator("//span[text()=' Skoda (3) ']").check();
  console.log(await page.locator("//span[text()=' Skoda (3) ']").textContent());
  await page.waitForTimeout(3000);
  const car12 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title12=await car12.allTextContents();
  console.log(title12.length);
  console.log(title12);
  await page.locator("//span[text()=' Skoda (3) ']").uncheck();
  await page.locator("//span[text()=' Tata (10) ']").check();
  console.log(await page.locator("//span[text()=' Tata (10) ']").textContent());
  await page.waitForTimeout(3000);
  const car13 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title13=await car13.allTextContents();
  console.log(title13.length);
  console.log(title13);
  await page.locator("//span[text()=' Tata (10) ']").uncheck();
  await page.locator("//span[text()=' Toyota (4) ']").check();
  console.log(await page.locator("//span[text()=' Toyota (4) ']").textContent());
  await page.waitForTimeout(3000);
  const car14 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title14=await car14.allTextContents();
  console.log(title14.length);
  console.log(title14);
  await page.locator("//span[text()=' Toyota (4) ']").uncheck();
  await page.locator("//span[text()=' Volkswagen (2) ']").check();
  console.log(await page.locator("//span[text()=' Volkswagen (2) ']").textContent());
  await page.waitForTimeout(3000);
  const car15 = page.locator("//a[@class='fieldvalue make-name ng-star-inserted']");
  const title15=await car15.allTextContents();
  console.log(title15.length);
  console.log(title15);
  await page.locator("//span[text()=' Volkswagen (2) ']").uncheck();
  test.setTimeout(70000);
  //Segment
 

 
 //await page.pause();
});
test('Segments', async ({page}) => {
  await page.goto('https://uat.quiklyz.com/');
  await page.locator('input[placeholder="Search Your City"]').fill('Chennai');
  await page.locator('.fg-line-form > div > div > .Chennai > div').first().click();
  await page.locator("(//a[@class='mat-focus-indicator mat-button mat-button-base ng-star-inserted'])[1]").click();
  await page.locator("//span[text()='Compact SUV ']").check();
  console.log( await page.locator('//div[@class="facebutton Compact SUV active"]').textContent());
  await page.waitForTimeout(3000);
  const car16 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title16=await car16.allTextContents();
  // console.log(title16.length);
  // console.log(title16);
  await page.locator('//a[text()=2]').click();
  await page.waitForTimeout(3000);
  const car28 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title28=await car28.allTextContents();
  const tot1=(title16.concat(title28));
  console.log(tot1.length);
  console.log(tot1);
  await page.locator('//div[@class="facebutton Compact SUV active"]').uncheck();
  test.setTimeout(70000);
  await page.locator('//div[@class="facebutton Hatchback"]').check();
  console.log(await page.locator('//div[@class="facebutton Hatchback active"]').textContent());
  await page.waitForTimeout(3000);
  const car17 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title17=await car17.allTextContents();
  // console.log(title17.length);
  // console.log(title17);
  await page.locator("//a[text()='2']").click();
  await page.waitForTimeout(3000);
  const car29 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title29=await car29.allTextContents();
  const tot2=title17.concat(title29);
  console.log(tot2.length);
  console.log(tot2);
  await page.locator('//div[@class="facebutton Hatchback active"]').uncheck();
  await page.locator('//div[@class="facebutton MUV"]').check();
  console.log(await page.locator('//div[@class="facebutton MUV active"]').textContent());
  await page.waitForTimeout(3000);
  const car18 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title18=await car18.allTextContents();
  console.log(title18.length);
  console.log(title18);
  await page.locator('//div[@class="facebutton MUV active"]').uncheck();
  await page.locator('//div[@class="facebutton SUV"]').check();
  console.log(await page.locator('//div[@class="facebutton SUV active"]').textContent());
  await page.waitForTimeout(3000);
  const car19 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title19=await car19.allTextContents();
  // console.log(title19.length);
  // console.log(title19);
  await page.locator("//a[text()='2']").click();
  await page.waitForTimeout(3000);
  const car30 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title30=await car30.allTextContents();
  // console.log(title30.length);
  // console.log(title30);
  await page.locator("//a[text()='3']").click();
  await page.waitForTimeout(3000);
  const car31 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title31=await car31.allTextContents();
  const tot3=title19.concat(title30,title31);
  console.log(tot3.length);
  console.log(tot3);
  await page.locator('//div[@class="facebutton SUV active"]').uncheck();
  await page.locator('//div[@class="facebutton Sedan"]').check();
  console.log(await page.locator('//div[@class="facebutton Sedan active"]').textContent());
  await page.waitForTimeout(3000);
  const car20 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title20=await car20.allTextContents();
  console.log(title20.length);
  console.log(title20);
  await page.locator('//div[@class="facebutton Sedan active"]').uncheck();
  //await page.locator("//span[text()=' Clear All ']").click();
  await page.locator("//span[text()=' AMT (21) ']").check();
  console.log(await page.locator("//span[text()=' AMT (21) ']").textContent());
  await page.waitForTimeout(3000);
  const car21 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title21=await car21.allTextContents();
  // console.log(title21.length);
  // console.log(title21);
  await page.locator("//a[text()='2']").click();
  await page.waitForTimeout(3000);
  const car32 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title32=await car32.allTextContents();
  const tot4=title21.concat(title32);
  console.log(tot4.length);
  console.log(tot4);
  test.setTimeout(70000);
  await page.waitForTimeout(3000);
  await page.locator("//span[text()=' AMT (21) ']").uncheck();
  await page.locator("//span[text()=' Automatic (51) ']").check();
  console.log(await page.locator("//span[text()=' Automatic (51) ']").textContent());
  await page.waitForTimeout(3000);
  const car22 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title22=await car22.allTextContents();
  // console.log(title22.length);
  // console.log(title22);
  await page.locator("//a[text()='2']").click();
  await page.waitForTimeout(3000);
  const car33 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title33=await car33.allTextContents();
  // console.log(title33.length);
  // console.log(title33);
  await page.locator("//a[text()='3']").click();
  await page.waitForTimeout(3000);
  const car34 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title34=await car34.allTextContents();
  // console.log(title34.length);
  // console.log(title34);
  await page.locator("//a[text()='4']").click();
  await page.waitForTimeout(3000);
  const car35 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title35=await car35.allTextContents();
  // console.log(title35.length);
  // console.log(title35);
  await page.locator("//a[text()='5']").click();
  await page.waitForTimeout(3000);
  const car36 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title36=await car36.allTextContents();
  const tot5=title22.concat(title33,title34,title35,title36);
  console.log(tot5.length);
  console.log(tot5);
  await page.locator("//span[text()=' Automatic (51) ']").uncheck();
  test.setTimeout(120000);
  await page.waitForTimeout(3000);
  await page.locator("//span[text()=' Manual (54) ']").check();
  console.log(await page.locator("//span[text()=' Manual (54) ']").textContent());
  await page.waitForTimeout(5000);
  const car23 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title23=await car23.allTextContents();
  // console.log(title23.length);
  // console.log(title23);
  await page.locator("//a[text()='2']").click();
  await page.waitForTimeout(3000);
  const car37 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title37=await car37.allTextContents();
  // console.log(title37.length);
  // console.log(title37);
  await page.locator("//a[text()='3']").click();
  await page.waitForTimeout(3000);
  const car38 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title38=await car38.allTextContents();
  // console.log(title38.length);
  // console.log(title38);
  await page.locator("//a[text()='4']").click();
  await page.waitForTimeout(3000);
  const car39 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title39=await car39.allTextContents();
  // console.log(title39.length);
  // console.log(title39);
  await page.locator("//a[text()='5']").click();
  await page.waitForTimeout(3000);
  const car40 = page.locator('//a[@class="fieldvalue make-name ng-star-inserted"]');
  const title40=await car40.allTextContents();
  const tot6=title23.concat(title37,title38,title39,title40);
  console.log(tot6.length);
  console.log(tot6);
  await page.locator("//span[text()=' Manual (54) ']").uncheck();
});
test('Fuel', async ({ page }) => {
  await page.goto('https://uat.quiklyz.com/');
  await page.locator('input[placeholder="Search Your City"]').fill('Chennai');
  await page.locator('.fg-line-form > div > div > .Chennai > div').first().click();
  await page.locator("(//a[@class='mat-focus-indicator mat-button mat-button-base ng-star-inserted'])[1]").click();
  await page.locator("//span[text()=' CNG (13) ']").check();
  console.log(await page.locator("//span[text()=' CNG (13) ']").textContent());
  await page.waitForTimeout(3000);
  const car24 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title24=await car24.allTextContents();
  // console.log(title24.length);
  // console.log(title24);
  await page.locator("//a[text()='2']").click();
  await page.waitForTimeout(3000);
  const car41 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title41=await car41.allTextContents();
  const tot7=title24.concat(title41);
  console.log(tot7.length);
  console.log(tot7);
  await page.locator("//span[text()=' CNG (13) ']").uncheck();
  await page.locator("//span[text()=' Diesel (26) ']").check();
  console.log(await page.locator("//span[text()=' Diesel (26) ']").textContent());
  await page.waitForTimeout(3000);
  const car25 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title25=await car25.allTextContents();
  // console.log(title25.length);
  // console.log(title25);
  await page.locator("//a[text()='2']").click();
  await page.waitForTimeout(3000);
  const car42 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title42=await car42.allTextContents();
  // console.log(title42.length);
  // console.log(title42);
  await page.locator("//a[text()='3']").click();
  await page.waitForTimeout(3000);
  const car43 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title43=await car43.allTextContents();
  const tot8=title25.concat(title42,title43);
  console.log(tot8.length);
  console.log(tot8);
  await page.locator("//span[text()=' Diesel (26) ']").uncheck();
  test.setTimeout(70000);
  await page.locator("//span[text()=' Electric (9) ']").check();
  console.log(await page.locator("//span[text()=' Electric (9) ']").textContent());
  await page.waitForTimeout(3000);
  const car26 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title26=await car26.allTextContents();
  console.log(title26.length);
  console.log(title26);
  await page.locator("//span[text()=' Electric (9) ']").uncheck();
  await page.locator("//span[text()=' Petrol (53) ']").check();
  console.log(await page.locator("//span[text()=' Petrol (53) ']").textContent());
  await page.waitForTimeout(3000);
  const car27 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title27=await car27.allTextContents();
  // console.log(title27.length);
  // console.log(title27);
  await page.locator("//a[text()='2']").click();
  await page.waitForTimeout(3000);
  const car44 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title44=await car44.allTextContents();
  // console.log(title44.length);
  // console.log(title44);
  await page.locator("//a[text()='3']").click();
  await page.waitForTimeout(3000);
  const car45 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title45=await car45.allTextContents();
  // console.log(title45.length);
  // console.log(title45);
  await page.locator("//a[text()='4']").click();
  await page.waitForTimeout(3000);
  const car46 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title46=await car46.allTextContents();
  // console.log(title46.length);
  // console.log(title46);
  await page.locator("//a[text()='5']").click();
  await page.waitForTimeout(3000);
  const car47 = page.locator('//div[@class="card galcard-3 noborder fgbox-shadow12 ng-star-inserted"]');
  const title47=await car47.allTextContents();
  const tot9=title27.concat(title44,title45,title46,title47);
  console.log(tot9.length);
  console.log(tot9);
  await page.locator("//span[text()=' Petrol (53) ']").uncheck();
  
});
// test('check my eligibility', async ({ page }) => {
//   await page.getByRole('button', { name: 'More ' }).click();
//   await page.getByRole('menuitem', { name: ' Check My Eligibility' }).click();


// });

/*test('How it work',async ({ page }) => {
  //How it work
  await page.locator("//span[text()='   How it Works   ']").click();
  await page.locator("//span[text()='Car Subscription Process']").click();
//await page.getByRole('menuitem', { name: ' Car Subscription Process' }).click();
  await page.locator('button').filter({ hasText: 'Browse Cars' }).click();
  await page.goBack();
  console.log( await page.getByRole('link', { name: 'quiklyz.service@mahindra.com' }).textContent());
  await page.goBack();
  test.setTimeout(130000);
  
});*/
/*test('FAQ',async ({ page }) => {
//   //FAQ
  await page.getByRole('link', { name: 'FAQs' }).click();
  console.log(await page.getByText('Frequently Asked Questions').textContent());
  await page.getByPlaceholder('Search your FAQ queries').fill('how is car leasing beneficial to your organisation?');
  await page.getByRole('button', { name: 'How is car leasing beneficial to your organisation?' }).click();
  console.log(await page.getByRole('button', { name: 'How is car leasing beneficial to your organisation?' }).textContent());
  await page.getByRole('button', { name: 'What exactly is Quiklyz Car Subscription?' }).click();
  console.log(await page.getByRole('button', { name: 'What exactly is Quiklyz Car Subscription?' }).textContent());
  await page.getByRole('button', { name: 'Why would I need to Quiklyz a car?' }).click();
  console.log(await page.getByRole('button', { name: 'Why would I need to Quiklyz a car?' }).textContent());
  await page.getByRole('button', { name: 'How is car leasing beneficial to your employee?' }).click();
  console.log(await page.getByRole('button', { name: 'How is car leasing beneficial to your employee?' }).textContent());
  await page.getByRole('button', { name: 'How is Quiklyz different from other self-drive and car rental services?' }).click();
  console.log(await page.getByRole('button', { name: 'How is Quiklyz different from other self-drive and car rental services?' }).textContent());
  await page.locator("//button[text()='View More']").click();
  test.setTimeout(130000);
  await page.getByRole('button', { name: 'How can quiklyz offer a complete lease solution?' }).click();
  console.log(await page.getByRole('button', { name: 'How can quiklyz offer a complete lease solution?' }).textContent());
  await page.getByRole('button', { name: 'Why should I choose Quiklyz? How are Quiklyz subscription prices compared to others?' }).click();
  console.log(await page.getByRole('button', { name: 'Why should I choose Quiklyz? How are Quiklyz subscription prices compared to others?' }).textContent());
  await page.getByRole('button', { name: 'How is Mahindra Finance Quiklyz unique?' }).click();
  console.log(await page.getByRole('button', { name: 'How is Mahindra Finance Quiklyz unique?' }).textContent());
  await page.getByRole('button', { name: 'What are the benefits of Quiklyz?' }).click();
  console.log(await page.getByRole('button', { name: 'What are the benefits of Quiklyz?' }).textContent());
  await page.getByRole('button', { name: 'How do I know if I am eligible to subscribe to a car on Quiklyz?' }).click();
  console.log(await page.getByRole('button', { name: 'How do I know if I am eligible to subscribe to a car on Quiklyz?' }).textContent());
  await page.getByRole('button', { name: 'What documents do I need to subscribe to a car on Quiklyz?' }).click();
  console.log(await page.getByRole('button', { name: 'What documents do I need to subscribe to a car on Quiklyz?' }).textContent());
  await page.getByRole('button', { name: 'What are the services included in my Quiklyz Car Subscription?' }).click();
  console.log(await page.getByRole('button', { name: 'What are the services included in my Quiklyz Car Subscription?' }).textContent());
  await page.getByRole('button', { name: 'How long will it take for Quiklyz to deliver my car to me?' }).click();
  console.log(await page.getByRole('button', { name: 'How long will it take for Quiklyz to deliver my car to me?' }).textContent());
  await page.getByRole('button', { name: 'Do I need to be physically present for taking the delivery of the car?' }).click();
  console.log(await page.getByRole('button', { name: 'Do I need to be physically present for taking the delivery of the car?' }).textContent());
  await page.getByRole('button', { name: 'Will Quiklyz manage my cars service and maintenance?' }).click();
  console.log(await page.getByRole('button', { name: 'Will Quiklyz manage my cars service and maintenance?' }).textContent());
  await page.getByRole('button', { name: 'Will Quiklyz manage my car\'s Insurance?' }).click();
  console.log(await page.getByRole('button', { name: 'Will Quiklyz manage my car\'s Insurance?' }).textContent());
  await page.getByRole('button', { name: 'What all will be covered in my Insurance?' }).click();
  console.log(await page.getByRole('button', { name: 'What all will be covered in my Insurance?' }).textContent());
  await page.getByRole('button', { name: 'Can I get a stand-by or replacement car on Quiklyz in case my car is off-road due to accidental damage or maintenance?' }).click();
  console.log(await page.getByRole('button', { name: 'Can I get a stand-by or replacement car on Quiklyz in case my car is off-road due to accidental damage or maintenance?' }).textContent());
  await page.getByRole('button', { name: 'Can I subscribe to a used car on Quiklyz?' }).click();
  console.log(await page.getByRole('button', { name: 'Can I subscribe to a used car on Quiklyz?' }).textContent());
  await page.getByRole('button', { name: 'How is car subscription different from car leasing?' }).click();
  console.log(await page.getByRole('button', { name: 'How is car subscription different from car leasing?' }).textContent());
  await page.getByRole('button', { name: 'Why does my agreement have \'Lease/ Leasing\' mentioned, instead of Subscription?' }).click();
  console.log(await page.getByRole('button', { name: 'Why does my agreement have \'Lease/ Leasing\' mentioned, instead of Subscription?' }).textContent());
  await page.getByRole('button', { name: 'How should I inform you of any changes in my contact details?' }).click();
  console.log(await page.getByRole('button', { name: 'How should I inform you of any changes in my contact details?' }).textContent());
  await page.getByRole('button', { name: 'View Less' }).click();
  await page.getByText('Expand All').click();
  //test.setTimeout(130000);
  await page.getByRole('tab', { name: 'Fees and Tenure' }).click();
  // await page.getByText('Expand All').click();
  // await page.getByText('Minimize All').click();
  await page.getByRole('tab', { name: 'Payments' }).click();
  // await page.getByText('Expand All').click();
  // await page.getByText('Minimize All').click();
  await page.getByText('About Car').click();
  // await page.getByText('Expand All').click();
  // await page.getByText('Minimize All').click();
  await page.getByText('Booking and Registration').click();
  // await page.getByText('Expand All').click();
  // await page.getByText('Minimize All').click();
  await page.getByText('Service and Maintenance').click();
  // await page.getByText('Expand All').click();
  // await page.getByText('Minimize All').click();
  await page.getByText('Guidelines').click();
  // await page.getByText('Expand All').click();
  // await page.getByText('Minimize All').click();
  await page.getByText('Assured Buyback').click();
  // await page.getByText('Expand All').click();
  // await page.getByText('Minimize All').click();
});*/
test('more',async ({ page }) => {
  //more
  //test.setTimeout(17000);
//   await page.getByRole('button', { name: 'More ' }).click();
//  //await page.getByRole('menuitem', { name: ' Check My Eligibility' }).click();
 //await page.locator("//span[text()='Compare Cars']").click();
 await page.goto('https://uat.quiklyz.com/car-leasing/compare');
await page.locator("(//mat-label[text()=' Select Brand '])[1]").click();
await page.locator("//span[text()=' Audi']").click();
await page.locator("(//mat-label[text()=' Select Model '])[1]").click();
await page.locator("//span[text()=' Audi e-tron ']").click();
await page.waitForTimeout(3000);
await page.locator("(//mat-label[text()=' Select Variant '])[1]").click();
await page.locator("(//span[text()=' e-tron 50 Electric Automatic Metallic Active'])[1]").click();
await page.locator('#mat-select-6 div').nth(2).click();
await page.waitForTimeout(3000);
await page.getByRole('option', { name: 'Skoda' }).locator('span').first().click();
await page.locator('#mat-select-8 div').nth(2).click();
await page.waitForTimeout(3000);
await page.getByRole('option', { name: 'Skoda Kodiaq' }).locator('span').first().click();
await page.locator('#mat-select-10 div').nth(3).click();
await page.waitForTimeout(3000);
await page.locator('#mat-option-57').getByText('Kodiaq Style AT Petrol Automatic Metallic Active').click();
await page.locator('#mat-select-12 div').nth(2).click();
await page.waitForTimeout(3000);
await page.getByRole('option', { name: 'Volkswagen' }).locator('span').first().click();
await page.getByRole('combobox', { name: 'Select Model', exact: true }).locator('div').nth(3).click();
await page.getByRole('listbox', { name: 'Select Model' }).locator('span').first().click();
await page.locator('#mat-select-16 div').nth(3).click();
  await page.pause();
});